apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: metallb-release
            path: metallb
            namespace: metallb-system
          - name: ingress-nginx
            path: ingress-nginx
            namespace: ingress-nginx
          - name: cert-manager
            path: cert-manager
            namespace: cert-manager
          - name: infisical
            path: infisical
            namespace: infisical
          - name: infisical-operator
            path: infisical-operator
            namespace: infisical
          - name: kargo
            path: kargo
            namespace: kargo
          - name: rook-ceph
            path: rook-ceph
            namespace: rook-ceph
          - name: prometheus-grafana
            path: prometheus-grafana
            namespace: monitoring
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Itsjoses/infrastructure-kube-argocd.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true