apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - name: infisical
          #   path: infisical
          #   namespace: infisical
          # - name: infisical-operator
          #   path: infisical-operator
          #   namespace: infisical
          # - name: prometheus-grafana
          #   path: prometheus-grafana
          #   namespace: monitoring
          # - name: metallb
          #   path: metallb
          #   namespace: metallb-system
          # - name: cert-manager
          #   path: cert-manager
          #   namespace: cert-manager
          - name: kargo
            path: kargo
            namespace: kargo
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Itsjoses/infrastructure-kube-argocd.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true