apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
type: Opaque
stringData:
  AUTH_SECRET: u0CXXebaxV9g8ABtK4PQx09UOCTJx58A29LYxrVG6fU= # ganti dengan secret yang diinginkan
  ENCRYPTION_KEY: 35c18208789c7e376796555c5619ddfe # ganti dengan encryption key yang diinginkan
  SITE_URL: http://localhost
