infisical:
  image:
    repository: infisical/infisical
    tag: "v0.159.13" # Check https://hub.docker.com/r/infisical/infisical/tags for latest
    pullPolicy: IfNotPresent
  replicaCount: 2

ingress:
  enabled: false
  nginx:
    enabled: false