apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.3
    - repoURL: https://github.com/Itsjoses/infrastructure-kube-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      enabled: true
      selfHeal: true
      prune: true
