apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-standalone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  sources:
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
      chart: infisical-standalone
      targetRevision: 1.8.0
      helm:
        releaseName: infisical
        valueFiles:
          - $values/stack/infisical/values.yaml
    - repoURL: https://github.com/Itsjoses/infrastructure-kube-argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

-- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-standalone
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Itsjoses/infrastructure-kube-argocd.git
    targetRevision: main
    path: addons/infisical
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

