apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://github.com/Itsjoses/infrastructure-kube-argocd.git
    targetRevision: main
    path: addons/infisical
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true